# Generated by Django 5.2.1 on 2026-03-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RekorAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('sakit', 'Sakit'), ('izin', 'Izin'), ('cuti', 'Cuti'), ('alpa', 'Alpa')], default='hadir', max_length=10, verbose_name='Status')),
                ('waktu_masuk', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Masuk')),
                ('lat_masuk', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude Masuk')),
                ('lon_masuk', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude Masuk')),
                ('foto_masuk', models.ImageField(blank=True, null=True, upload_to='absensi/foto/', verbose_name='Foto Masuk (Selfie)')),
                ('waktu_keluar', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Keluar')),
                ('lat_keluar', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude Keluar')),
                ('lon_keluar', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude Keluar')),
                ('foto_keluar', models.ImageField(blank=True, null=True, upload_to='absensi/foto/', verbose_name='Foto Keluar (Selfie)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rekap Absensi',
                'verbose_name_plural': 'Rekap Absensi',
                'ordering': ['-tanggal', '-waktu_masuk'],
            },
        ),
    ]
