# Generated by Django 5.2.1 on 2026-03-10 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absensi', '0001_initial'),
        ('sprin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rekorabsensi',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_absensi', to=settings.AUTH_USER_MODEL, verbose_name='Personel'),
        ),
        migrations.AddField(
            model_name='rekorabsensi',
            name='sprin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi', to='sprin.sprin', verbose_name='Sprin Terkait'),
        ),
        migrations.AlterUniqueTogether(
            name='rekorabsensi',
            unique_together={('personel', 'tanggal', 'sprin')},
        ),
    ]
