# Generated by Django 5.2.1 on 2026-03-10 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul')),
                ('pesan', models.TextField(verbose_name='Pesan')),
                ('tipe', models.CharField(choices=[('cuti_status', 'Update Status Cuti'), ('sprin_baru', 'Sprin Baru'), ('pengajuan_masuk', 'Pengajuan Cuti Masuk'), ('surat_diterbitkan', 'Surat Resmi Diterbitkan'), ('umum', 'Umum')], default='umum', max_length=30, verbose_name='Tipe')),
                ('url_ref', models.CharField(blank=True, max_length=300, verbose_name='URL Referensi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL, verbose_name='Penerima')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
