# Generated by Django 5.2.1 on 2026-03-10 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_cuti', models.CharField(choices=[('tahunan', 'Cuti Tahunan'), ('sakit', 'Cuti Sakit'), ('alasan_penting', 'Cuti Alasan Penting'), ('besar', 'Cuti Besar'), ('di_luar_tanggungan', 'Cuti di Luar Tanggungan Negara')], max_length=30, verbose_name='Jenis Cuti')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('alasan', models.TextField(verbose_name='Alasan / Keterangan')),
                ('dokumen_pendukung', models.FileField(blank=True, null=True, upload_to='cuti/dokumen/', verbose_name='Dokumen Pendukung (JPG/PNG/PDF)')),
                ('file_surat_resmi', models.FileField(blank=True, null=True, upload_to='cuti/surat_resmi/', verbose_name='Surat Cuti Resmi (upload SDM)')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=15, verbose_name='Status')),
                ('catatan_pimpinan', models.TextField(blank=True, verbose_name='Catatan Pimpinan')),
                ('diajukan_pada', models.DateTimeField(auto_now_add=True, verbose_name='Diajukan Pada')),
                ('diproses_pada', models.DateTimeField(blank=True, null=True, verbose_name='Diproses Pada')),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuti_disetujui', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_cuti', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Pengajuan Cuti',
                'verbose_name_plural': 'Pengajuan Cuti',
                'ordering': ['-diajukan_pada'],
            },
        ),
    ]
