# Generated by Django 6.0.3 on 2026-04-25 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Satuan Kerja',
                'verbose_name_plural': 'Satuan Kerja',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='Path / URL Name')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='accounts.menuitem', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Role')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('dibuat_pada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dibuat Pada')),
                ('display_label', models.CharField(blank=True, max_length=100, verbose_name='Display Label')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='accounts.menuitem', verbose_name='Menu Access')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Role',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nrp', models.CharField(max_length=20, unique=True, verbose_name='NRP')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('no_hp', models.CharField(blank=True, max_length=20, verbose_name='No. HP')),
                ('pangkat', models.CharField(blank=True, choices=[('Bharada', 'Bharada'), ('Bhayangkara', 'Bhayangkara'), ('Bripda', 'Bripda'), ('Briptu', 'Briptu'), ('Brigpol', 'Brigpol'), ('Bripka', 'Bripka'), ('Aipda', 'Aipda'), ('Aiptu', 'Aiptu'), ('Ipda', 'Ipda'), ('Iptu', 'Iptu'), ('AKP', 'AKP'), ('Kompol', 'Kompol'), ('AKBP', 'AKBP'), ('Kombespol', 'Kombespol'), ('Brigjen Pol', 'Brigjen Pol'), ('Irjen Pol', 'Irjen Pol'), ('Komjen Pol', 'Komjen Pol'), ('Jenderal Pol', 'Jenderal Pol')], max_length=50, verbose_name='Pangkat')),
                ('jabatan', models.CharField(blank=True, max_length=200, verbose_name='Jabatan')),
                ('role', models.CharField(choices=[('personel', 'Personel'), ('operator', 'Operator'), ('pimpinan', 'Pimpinan'), ('superadmin', 'Superadmin')], default='personel', max_length=20, verbose_name='Role')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_personel/', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=False)),
                ('status_verifikasi', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('tanggal_bergabung', models.DateTimeField(auto_now_add=True)),
                ('tanggal_nonaktif', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Dinonaktifkan')),
                ('alasan_nonaktif', models.TextField(blank=True, verbose_name='Alasan Dinonaktifkan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel_set', to='accounts.role', verbose_name='Role (Object)')),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel', to='accounts.satker', verbose_name='Satuan Kerja')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personel',
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
