# Generated by Django 5.2.1 on 2026-03-10 21:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Role')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('dibuat_pada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Role',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='personel',
            name='role_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel_set', to='accounts.role', verbose_name='Role (Object)'),
        ),
    ]
