# Generated by Django 5.2.1 on 2026-03-10 21:10
#
# 1) State-only: Role + role_obj (so RunPython can use historical models)
# 2) RunPython: idempotent DB — skip create/add if the table / column already exists

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _forwards(apps, schema_editor):
    # After the SeparateDatabaseAndState state step, apps includes Role and role_obj on Personel.
    Role = apps.get_model("accounts", "Role")
    Personel = apps.get_model("accounts", "Personel")
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        all_tables = set(connection.introspection.table_names(cursor))

    if Role._meta.db_table not in all_tables:
        schema_editor.create_model(Role)

    field = Personel._meta.get_field("role_obj")
    with connection.cursor() as cursor:
        columns = {
            c.name
            for c in connection.introspection.get_table_description(
                cursor, Personel._meta.db_table
            )
        }
    if field.column not in columns:
        schema_editor.add_field(Personel, field)


def _backwards(apps, schema_editor):
    Personel = apps.get_model("accounts", "Personel")
    Role = apps.get_model("accounts", "Role")
    field = Personel._meta.get_field("role_obj")
    schema_editor.remove_field(Personel, field)
    schema_editor.delete_model(Role)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Role",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "nama",
                            models.CharField(
                                max_length=100, unique=True, verbose_name="Nama Role"
                            ),
                        ),
                        (
                            "deskripsi",
                            models.TextField(blank=True, verbose_name="Deskripsi"),
                        ),
                        (
                            "dibuat_pada",
                            models.DateTimeField(
                                default=django.utils.timezone.now,
                                verbose_name="Dibuat Pada",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Role",
                        "verbose_name_plural": "Role",
                        "ordering": ["nama"],
                    },
                ),
                migrations.AddField(
                    model_name="personel",
                    name="role_obj",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personel_set",
                        to="accounts.role",
                        verbose_name="Role (Object)",
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(_forwards, _backwards),
    ]
