# Generated by Django 5.2.1 on 2026-04-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_personel_role_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='alasan_nonaktif',
            field=models.TextField(blank=True, verbose_name='Alasan Dinonaktifkan'),
        ),
        migrations.AddField(
            model_name='personel',
            name='tanggal_nonaktif',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Dinonaktifkan'),
        ),
    ]
