# Generated by Django 5.2.1 on 2026-04-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_menuitem_role_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='display_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Display Label'),
        ),
    ]
