# Generated by Django 5.2.1 on 2026-04-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_display_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='status_verifikasi',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='personel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
