# Generated by Django 5.2.1 on 2026-05-17 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_personel_status_verifikasi_alter_personel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='display_label',
        ),
        migrations.CreateModel(
            name='AccountStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_baru', models.BooleanField(verbose_name='Status Baru')),
                ('alasan', models.TextField(verbose_name='Alasan Perubahan')),
                ('waktu_perubahan', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Perubahan')),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Riwayat Status Akun',
                'verbose_name_plural': 'Riwayat Status Akun',
                'ordering': ['-waktu_perubahan'],
            },
        ),
    ]
