# Generated by Django 6.0.3 on 2026-04-25 06:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('tanggal_publikasi', models.DateTimeField(default=django.utils.timezone.now)),
                ('periode_mulai', models.DateTimeField(blank=True, null=True)),
                ('periode_selesai', models.DateTimeField(blank=True, null=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dibaca_oleh', models.ManyToManyField(blank=True, related_name='pengumuman_dibaca', to=settings.AUTH_USER_MODEL)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengumuman_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pengumuman_pengumuman',
                'ordering': ['-tanggal_publikasi'],
            },
        ),
    ]
