# Generated by Django 5.2.1 on 2026-03-10 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300, verbose_name='Judul')),
                ('konten', models.TextField(verbose_name='Isi Konten')),
                ('lampiran', models.FileField(blank=True, null=True, upload_to='pengumuman/lampiran/', verbose_name='Lampiran (Gambar/PDF)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Dipublikasikan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengumuman', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
