# Generated by Django 5.2.1 on 2026-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0002_pengumuman_dibaca_oleh'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='tanggal_pelaksanaan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
