# Generated by Django 5.2.1 on 2026-04-22 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_display_label'),
        ('manajemen_cuti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuancuti',
            name='satuan_kerja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_cuti', to='accounts.satker', verbose_name='Satuan Kerja'),
        ),
    ]
