# Generated by Django 6.0.3 on 2026-03-11 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personel', '0002_auto_20260310_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Office Hour', 'Office Hour'), ('Dinas', 'Dinas'), ('Izin', 'Izin')], max_length=20)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkin_photo', models.ImageField(blank=True, null=True, upload_to='presensi/foto_masuk/')),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('checkout_photo', models.ImageField(blank=True, null=True, upload_to='presensi/foto_keluar/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='presensi/dokumen/')),
                ('izin_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Alfa', max_length=20)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.personel')),
            ],
            options={
                'unique_together': {('personel', 'date')},
            },
        ),
    ]
