# Generated by Django 6.0.3 on 2026-04-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('presensi', '0002_align_personel_fk_to_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='catatan',
            field=models.TextField(blank=True, verbose_name='Catatan presensi'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='checkin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presensi_checkins', to='locations.location', verbose_name='Lokasi check-in (GPS terdekat)'),
        ),
    ]
