# Generated by Django 6.0.3 on 2026-04-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0003_checkin_location_and_catatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presensi',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='presensi',
            name='checkin_location',
        ),
    ]
