# Generated by Django 5.2.1 on 2026-03-10 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=100, unique=True, verbose_name='Nomor Sprin')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('perihal', models.CharField(max_length=300, verbose_name='Perihal / Operasi')),
                ('dasar', models.TextField(blank=True, verbose_name='Dasar')),
                ('isi_perintah', models.TextField(blank=True, verbose_name='Isi Perintah')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('menunggu_paraf', 'Menunggu Paraf'), ('aktif', 'Aktif'), ('selesai', 'Selesai')], default='draft', max_length=20, verbose_name='Status')),
                ('file_sprin', models.FileField(blank=True, null=True, upload_to='sprin/', verbose_name='File Sprin (PDF)')),
                ('lat_lokasi', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude Lokasi')),
                ('lon_lokasi', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude Lokasi')),
                ('radius_meter', models.IntegerField(default=100, verbose_name='Radius Presensi (meter)')),
                ('waktu_mulai', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_dibuat', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('pejabat_penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_ditandatangani', to=settings.AUTH_USER_MODEL, verbose_name='Pejabat Penandatangan')),
            ],
            options={
                'verbose_name': 'Surat Perintah (Sprin)',
                'verbose_name_plural': 'Surat Perintah (Sprin)',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='PersonelSprin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_urut', models.PositiveIntegerField(default=1, verbose_name='Nomor Urut')),
                ('jabatan_dalam_sprin', models.CharField(blank=True, max_length=200, verbose_name='Jabatan dalam Sprin')),
                ('keterangan', models.CharField(blank=True, max_length=300, verbose_name='Keterangan')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penugasan', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
                ('sprin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_list', to='sprin.sprin', verbose_name='Sprin')),
            ],
            options={
                'verbose_name': 'Personel dalam Sprin',
                'verbose_name_plural': 'Personel dalam Sprin',
                'ordering': ['nomor_urut'],
                'unique_together': {('sprin', 'personel')},
            },
        ),
    ]
