# Generated by Django 6.0.3 on 2026-03-11 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personel', '0002_auto_20260310_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprin',
            fields=[
                ('id_sprin', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('radius_meter', models.IntegerField(default=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu Persetujuan', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_pimpinan', to='personel.personel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_dibuat', to='personel.personel')),
            ],
        ),
        migrations.CreateModel(
            name='PersonelSprin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penugasan_sprin', to='personel.personel')),
                ('sprin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_personel', to='sprin.sprin')),
            ],
            options={
                'unique_together': {('sprin', 'personel')},
            },
        ),
    ]
