# Generated by Django 6.0.3 on 2026-04-25 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprin',
            fields=[
                ('id_sprin', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu Persetujuan', max_length=25)),
                ('rejection_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_surat', models.FileField(blank=True, null=True, upload_to='sprin_pdf/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_pimpinan', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonelSprin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penugasan_sprin', to=settings.AUTH_USER_MODEL)),
                ('sprin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_personel', to='sprin.sprin')),
            ],
            options={
                'unique_together': {('sprin', 'personel')},
            },
        ),
    ]
