# Generated by Django 5.2.1 on 2026-03-10 21:36
# NOTE:
# This migration file came from a divergent history and conflicted with
# the active migration chain. It is intentionally converted into a no-op
# to preserve migration history compatibility while avoiding incompatible
# schema operations from the divergent branch.
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
