# Generated by Django 5.2.1 on 2026-03-10 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sprin',
            name='alasan_batal',
            field=models.TextField(blank=True, verbose_name='Alasan Pembatalan'),
        ),
        migrations.AddField(
            model_name='sprin',
            name='catatan_pimpinan',
            field=models.TextField(blank=True, verbose_name='Catatan Pimpinan (jika ditolak)'),
        ),
        migrations.AddField(
            model_name='sprin',
            name='dibatalkan_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_dibatalkan', to=settings.AUTH_USER_MODEL, verbose_name='Dibatalkan Oleh'),
        ),
        migrations.AddField(
            model_name='sprin',
            name='dibatalkan_pada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Pembatalan'),
        ),
        migrations.AddField(
            model_name='sprin',
            name='disetujui_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_disetujui', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui/Ditolak Oleh'),
        ),
        migrations.AddField(
            model_name='sprin',
            name='disetujui_pada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Persetujuan'),
        ),
        migrations.AddField(
            model_name='sprin',
            name='lokasi_penugasan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Lokasi Penugasan'),
        ),
        migrations.AlterField(
            model_name='sprin',
            name='file_sprin',
            field=models.FileField(blank=True, null=True, upload_to='sprin/', verbose_name='File Lampiran (PDF/JPG/PNG)'),
        ),
        migrations.AlterField(
            model_name='sprin',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('menunggu_paraf', 'Menunggu Paraf'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('aktif', 'Aktif'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
