# Generated by Django 6.0.3 on 2026-03-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprin',
            name='file_surat',
            field=models.FileField(blank=True, null=True, upload_to='sprin_pdf/'),
        ),
    ]
