# Generated by Django 6.0.3 on 2026-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0002_sprin_file_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprin',
            name='rejection_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
