# Generated by Django 6.0.3 on 2026-03-11 11:38
#
# SQLite does not support "ALTER TABLE ... DROP COLUMN IF EXISTS" (PostgreSQL syntax).
# Use schema_editor.remove_field + optional raw drop for orphan columns.

from django.core.exceptions import FieldDoesNotExist
from django.db import migrations


def drop_legacy_location_columns(apps, schema_editor):
    Sprin = apps.get_model("sprin", "Sprin")
    table = Sprin._meta.db_table
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing = {
            c.name
            for c in connection.introspection.get_table_description(cursor, table)
        }

    for name in ("latitude", "longitude", "radius_meter"):
        if name not in existing:
            continue
        try:
            field = Sprin._meta.get_field(name)
        except FieldDoesNotExist:
            tq = connection.ops.quote_name(table)
            nq = connection.ops.quote_name(name)
            if connection.vendor == "sqlite":
                schema_editor.execute(
                    f"ALTER TABLE {tq} DROP COLUMN {nq}"
                )
            else:
                schema_editor.execute(
                    f"ALTER TABLE {tq} DROP COLUMN IF EXISTS {nq}"
                )
            continue
        schema_editor.remove_field(Sprin, field)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("sprin", "0003_sprin_rejection_notes"),
    ]

    operations = [
        migrations.RunPython(drop_legacy_location_columns, noop_reverse),
    ]
