# Generated by Django 6.0.3 on 2026-03-11 11:38

from django.db import migrations


def drop_legacy_location_columns(apps, schema_editor):
    Sprin = apps.get_model('sprin', 'Sprin')
    table_name = Sprin._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    for field_name in ('latitude', 'longitude', 'radius_meter'):
        if field_name in columns:
            schema_editor.remove_field(Sprin, Sprin._meta.get_field(field_name))


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0003_sprin_rejection_notes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=drop_legacy_location_columns,
                    reverse_code=noop_reverse,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='sprin',
                    name='latitude',
                ),
                migrations.RemoveField(
                    model_name='sprin',
                    name='longitude',
                ),
                migrations.RemoveField(
                    model_name='sprin',
                    name='radius_meter',
                ),
            ],
        ),
    ]
