# Generated by Django 6.0.3 on 2026-03-11 11:38

from django.db import migrations


def drop_legacy_location_columns(apps, schema_editor):
    Sprin = apps.get_model('sprin', 'Sprin')
    table_name = Sprin._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    for field_name in ('latitude', 'longitude', 'radius_meter'):
        if field_name in columns:
            schema_editor.remove_field(Sprin, Sprin._meta.get_field(field_name))


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0003_sprin_rejection_notes'),
    ]

    operations = [
        # Use RunSQL to safely drop columns if they exist.
        # This prevents the "UndefinedColumn" error when the database state
        # is out of sync with migration history.
        migrations.RunSQL(
            "ALTER TABLE sprin_sprin DROP COLUMN IF EXISTS latitude;",
            reverse_sql="ALTER TABLE sprin_sprin ADD COLUMN IF NOT EXISTS latitude DECIMAL(12, 9) NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE sprin_sprin DROP COLUMN IF EXISTS longitude;",
            reverse_sql="ALTER TABLE sprin_sprin ADD COLUMN IF NOT EXISTS longitude DECIMAL(12, 9) NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE sprin_sprin DROP COLUMN IF EXISTS radius_meter;",
            reverse_sql="ALTER TABLE sprin_sprin ADD COLUMN IF NOT EXISTS radius_meter INTEGER DEFAULT 100;"
        ),
    ]
