# Generated by Django 5.2.1 on 2026-03-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0002_sprin_alasan_batal_sprin_catatan_pimpinan_and_more'),
        ('sprin', '0004_remove_sprin_latitude_remove_sprin_longitude_and_more'),
    ]

    operations = []
