# Generated by Django 5.2.1 on 2026-03-16 20:05

from django.db import migrations


def align_sprin_pk_column(apps, schema_editor):
    table_name = "sprin_sprin"
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        columns = {
            col.name
            for col in connection.introspection.get_table_description(cursor, table_name)
        }

    # Legacy schema used `id` as PK; current model expects `id_sprin`.
    if "id_sprin" not in columns and "id" in columns:
        schema_editor.execute(
            'ALTER TABLE "sprin_sprin" RENAME COLUMN "id" TO "id_sprin";'
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("sprin", "0005_merge_20260316_1845"),
    ]

    operations = [
        migrations.RunPython(
            code=align_sprin_pk_column,
            reverse_code=noop_reverse,
        ),
    ]
