# Generated by Django 5.2.1 on 2026-04-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0005_merge_20260316_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sprin',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sprin',
            name='radius_meter',
        ),
    ]
