# Generated by Django 5.2.1 on 2026-04-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0006_remove_sprin_latitude_remove_sprin_longitude_and_more'),
        ('sprin', '0006_rename_id_column_if_needed'),
    ]

    operations = [
    ]
