# Generated by Django 5.2.1 on 2026-04-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0007_merge_20260422_1916'),
        ('sprin', '0007_merge_20260422_2008'),
    ]

    operations = [
    ]
