# Generated by Django 6.0.3 on 2026-04-23 22:24
#
# RemoveField on DB can fail on SQLite if columns were already dropped by
# 0004_runpython. Update migration state with RemoveField; drop columns only
# when they still exist (introspection, no get_field on removed state).

from django.db import migrations


def _drop_sprin_location_columns_if_present(apps, schema_editor):
    table = "sprin_sprin"
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        existing = {
            c.name
            for c in connection.introspection.get_table_description(cursor, table)
        }
    tq = connection.ops.quote_name(table)
    for name in ("latitude", "longitude", "radius_meter"):
        if name not in existing:
            continue
        nq = connection.ops.quote_name(name)
        if connection.vendor == "sqlite":
            schema_editor.execute(f"ALTER TABLE {tq} DROP COLUMN {nq}")
        else:
            schema_editor.execute(
                f"ALTER TABLE {tq} DROP COLUMN IF EXISTS {nq}"
            )


def _noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("sprin", "0008_merge_20260422_2114"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="sprin",
                    name="latitude",
                ),
                migrations.RemoveField(
                    model_name="sprin",
                    name="longitude",
                ),
                migrations.RemoveField(
                    model_name="sprin",
                    name="radius_meter",
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _drop_sprin_location_columns_if_present,
                    _noop,
                ),
            ],
        ),
    ]
