# Generated by Django 6.0.3 on 2026-04-23 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0009_remove_sprin_latitude_remove_sprin_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personelsprin',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penugasan_sprin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sprin',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_pimpinan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sprin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprin_dibuat', to=settings.AUTH_USER_MODEL),
        ),
    ]
