# Generated by Django 5.2.1 on 2026-04-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprin', '0007_merge_20260426_2152'),
        ('sprin', '0010_align_personel_fk_to_auth_user'),
    ]

    operations = [
    ]
