# Generated by Django 6.0.3 on 2026-03-10 05:39

from django.db import migrations

def update_units(apps, schema_editor):
    Unit = apps.get_model('personel', 'Unit')
    units = [
        "Kepala Korps Lalu Lintas",
        "Seksi Keuangan",
        "Tata Urusan Dalam",
        "Bagian Operasi",
        "Bagian Perencanaan dan Administrasi",
        "Bagian Teknologi Informasi dan Komunikasi",
        "Direktorat Keamanan dan Keselamatan",
        "Direktorat Penegakan Hukum",
        "Direktorat Registrasi dan Identifikasi",
    ]
    for unit_name in units:
        Unit.objects.get_or_create(nama=unit_name)

    try:
        from django.db.models import ProtectedError
        for unit in Unit.objects.exclude(nama__in=units):
            try:
                unit.delete()
            except ProtectedError:
                pass
    except Exception:
        pass

def reverse_units(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_units, reverse_units),
    ]
