# Generated by Django 6.0.3 on 2026-04-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nama Lokasi')),
                ('type', models.CharField(choices=[('pos', 'Pos'), ('mako', 'Mako')], max_length=10, verbose_name='Tipe')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('radius', models.IntegerField(default=100, verbose_name='Radius (meter)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Wilayah Penugasan',
                'verbose_name_plural': 'Wilayah Penugasan',
                'ordering': ['-created_at'],
            },
        ),
    ]
